name: Maven Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
        default: 'X.Y.Z'
      developmentVersion:
        description: 'Next development version'
        required: true
        default: 'X.Y.Z-SNAPSHOT'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          server-id: github
          settings-path: ~/.m2/settings.xml

      - name: Configure Git User
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --yes --passphrase-fd 0 --edit-key F9472EB971E78100 trust quit
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build with Maven
        run: ./mvnw clean install -DskipTests

      - name: Maven Release
        run: |
          ./mvnw --file pom.xml -e release:prepare -B -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}  -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" -Darguments="-DskipTests"
          ./mvnw --file pom.xml -e release:perform -B -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" -Darguments="-DskipTests"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
